version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
     - POSTGRES_DB=store
     - POSTGRES_USER=gilbert
     - POSTGRES_PASSWORD=123456
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  pgadmin:
      image: dpage/pgadmin4
      environment:
       - PGADMIN_DEFAULT_EMAIL=gilbertferney@gmail.com
       - PGADMIN_DEFAULT_PASSWORD=123456
      ports:
        - "5050:80"